{
  "name": "SeismicRiskModel",
  "compatibilityLevel": 1500,
  "model": {
    "culture": "en-US",
    "collation": "Latin1_General_CI_AS",

    "dataSources": [
      {
        "type": "structured",
        "name": "SeismicDisasterDWH",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "localhost",
            "database": "SeismicDisasterDWH"
          }
        },
        "credential": {
          "AuthenticationKind": "Windows"
        }
      }
    ],

    "tables": [

      {
        "name": "DimDate",
        "dataCategory": "Time",
        "isHidden": false,
        "columns": [
          { "name": "DateKey",        "dataType": "int64",   "sourceColumn": "DateKey",       "isKey": true },
          { "name": "Date",           "dataType": "dateTime","sourceColumn": "Date" },
          { "name": "Year",           "dataType": "int64",   "sourceColumn": "Year" },
          { "name": "Quarter",        "dataType": "int64",   "sourceColumn": "Quarter" },
          { "name": "Month",          "dataType": "int64",   "sourceColumn": "Month" },
          { "name": "MonthName",      "dataType": "string",  "sourceColumn": "MonthName" },
          { "name": "MonthNameShort", "dataType": "string",  "sourceColumn": "MonthNameShort" },
          { "name": "Day",            "dataType": "int64",   "sourceColumn": "Day" },
          { "name": "DayWeek",        "dataType": "int64",   "sourceColumn": "DayWeek" },
          { "name": "DayWeekName",    "dataType": "string",  "sourceColumn": "DayWeekName" },
          { "name": "DayYear",        "dataType": "int64",   "sourceColumn": "DayYear" },
          { "name": "WeekYear",       "dataType": "int64",   "sourceColumn": "WeekYear" },
          { "name": "QuarterLabel",   "dataType": "string",  "type": "calculated",
            "expression": "\"Q\" & [Quarter] & \" \" & [Year]" }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "levels": [
              { "name": "Year",    "column": "Year",    "ordinal": 0 },
              { "name": "Quarter", "column": "QuarterLabel", "ordinal": 1 },
              { "name": "Month",   "column": "MonthName",    "ordinal": 2 },
              { "name": "Day",     "column": "Date",         "ordinal": 3 }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DimDate",
            "source": { "type": "m", "expression": [ "let Source = SeismicDisasterDWH{[Schema=\"dbo\",Item=\"DimDate\"]}[Data] in Source" ] }
          }
        ]
      },

      {
        "name": "DimGeography",
        "columns": [
          { "name": "GeographyKey",    "dataType": "int64",  "sourceColumn": "GeographyKey", "isKey": true },
          { "name": "CountryName",     "dataType": "string", "sourceColumn": "CountryName" },
          { "name": "ISO",             "dataType": "string", "sourceColumn": "ISO" },
          { "name": "SubRegion",       "dataType": "string", "sourceColumn": "SubRegion" },
          { "name": "Region",          "dataType": "string", "sourceColumn": "Region" },
          { "name": "IsCurrent",       "dataType": "boolean","sourceColumn": "IsCurrent" },
          { "name": "GeoSeismicZone",  "dataType": "string", "sourceColumn": "GeoSeismicZone" },
          { "name": "GEM_PGA_g",       "dataType": "decimal","sourceColumn": "GEM_PGA_g" },
          { "name": "CountryDurableKey","dataType": "int64", "sourceColumn": "CountryDurableKey" }
        ],
        "hierarchies": [
          {
            "name": "Geography Hierarchy",
            "levels": [
              { "name": "Region",          "column": "Region",         "ordinal": 0 },
              { "name": "Sub-Region",      "column": "SubRegion",      "ordinal": 1 },
              { "name": "Country",         "column": "CountryName",    "ordinal": 2 }
            ]
          },
          {
            "name": "Seismic Zone Hierarchy",
            "levels": [
              { "name": "Seismic Zone",    "column": "GeoSeismicZone", "ordinal": 0 },
              { "name": "Country",         "column": "CountryName",    "ordinal": 1 }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DimGeography",
            "source": {
              "type": "m",
              "expression": [ "let Source = SeismicDisasterDWH{[Schema=\"dbo\",Item=\"DimGeography\"]}[Data], Current = Table.SelectRows(Source, each [IsCurrent] = true) in Current" ]
            }
          }
        ]
      },

      {
        "name": "DimMagnitude",
        "columns": [
          { "name": "MagnitudeKey", "dataType": "int64",  "sourceColumn": "MagnitudeKey", "isKey": true },
          { "name": "BandCode",     "dataType": "string", "sourceColumn": "BandCode" },
          { "name": "BandName",     "dataType": "string", "sourceColumn": "BandName" },
          { "name": "LowerBound",   "dataType": "decimal","sourceColumn": "LowerBound" },
          { "name": "UpperBound",   "dataType": "decimal","sourceColumn": "UpperBound" },
          { "name": "MagScale",     "dataType": "string", "sourceColumn": "MagScale" }
        ],
        "partitions": [
          { "name": "DimMagnitude", "source": { "type": "m", "expression": [ "SeismicDisasterDWH{[Schema=\"dbo\",Item=\"DimMagnitude\"]}[Data]" ] } }
        ]
      },

      {
        "name": "DimSeismicDepth",
        "columns": [
          { "name": "SeismicDepthKey","dataType": "int64",  "sourceColumn": "SeismicDepthKey","isKey": true },
          { "name": "BandName",       "dataType": "string", "sourceColumn": "BandName" },
          { "name": "LowerBoundKM",   "dataType": "int64",  "sourceColumn": "LowerBoundKM" },
          { "name": "UpperBoundKM",   "dataType": "int64",  "sourceColumn": "UpperBoundKM" }
        ],
        "partitions": [
          { "name": "DimSeismicDepth", "source": { "type": "m", "expression": [ "SeismicDisasterDWH{[Schema=\"dbo\",Item=\"DimSeismicDepth\"]}[Data]" ] } }
        ]
      },

      {
        "name": "DimSeverityDeaths",
        "columns": [
          { "name": "SeverityDeathsKey","dataType": "int64",  "sourceColumn": "SeverityDeathsKey","isKey": true },
          { "name": "SeverityCode",     "dataType": "string", "sourceColumn": "SeverityCode" },
          { "name": "LowerBound",       "dataType": "int64",  "sourceColumn": "LowerBound" },
          { "name": "UpperBound",       "dataType": "int64",  "sourceColumn": "UpperBound" }
        ],
        "partitions": [
          { "name": "DimSeverityDeaths", "source": { "type": "m", "expression": [ "SeismicDisasterDWH{[Schema=\"dbo\",Item=\"DimSeverityDeaths\"]}[Data]" ] } }
        ]
      },

      {
        "name": "DimSeverityAffected",
        "columns": [
          { "name": "SeverityAffectedKey","dataType": "int64",  "sourceColumn": "SeverityAffectedKey","isKey": true },
          { "name": "SeverityCode",       "dataType": "string", "sourceColumn": "SeverityCode" },
          { "name": "LowerBound",         "dataType": "int64",  "sourceColumn": "LowerBound" },
          { "name": "UpperBound",         "dataType": "int64",  "sourceColumn": "UpperBound" }
        ],
        "partitions": [
          { "name": "DimSeverityAffected", "source": { "type": "m", "expression": [ "SeismicDisasterDWH{[Schema=\"dbo\",Item=\"DimSeverityAffected\"]}[Data]" ] } }
        ]
      },

      {
        "name": "FactSeismic",
        "columns": [
          { "name": "SeismicKey",                "dataType": "int64",   "sourceColumn": "SeismicKey",                "isKey": true },
          { "name": "DateKey",                   "dataType": "int64",   "sourceColumn": "DateKey" },
          { "name": "GeographyKey",              "dataType": "int64",   "sourceColumn": "GeographyKey" },
          { "name": "MagnitudeKey",              "dataType": "int64",   "sourceColumn": "MagnitudeKey" },
          { "name": "SeismicDepthKey",           "dataType": "int64",   "sourceColumn": "SeismicDepthKey" },
          { "name": "Latitude",                  "dataType": "decimal", "sourceColumn": "Latitude" },
          { "name": "Longitude",                 "dataType": "decimal", "sourceColumn": "Longitude" },
          { "name": "Magnitude",                 "dataType": "decimal", "sourceColumn": "Magnitude",     "summarizeBy": "none" },
          { "name": "SeismicDepth",              "dataType": "decimal", "sourceColumn": "SeismicDepth",  "summarizeBy": "none" },
          { "name": "ModifiedMercalliIntensity", "dataType": "decimal", "sourceColumn": "ModifiedMercalliIntensity", "summarizeBy": "none" },
          { "name": "SignificanceScore",         "dataType": "int64",   "sourceColumn": "SignificanceScore",         "summarizeBy": "none" },
          { "name": "CommunityDecimalIntensity", "dataType": "decimal", "sourceColumn": "CommunityDecimalIntensity", "summarizeBy": "none" }
        ],
        "measures": [
          {
            "name": "Liczba wstrząsów",
            "expression": "COUNTROWS ( FactSeismic )",
            "formatString": "#,##0",
            "description": "Całkowita liczba zarejestrowanych zdarzeń sejsmicznych."
          },
          {
            "name": "Średnia magnituda",
            "expression": "AVERAGE ( FactSeismic[Magnitude] )",
            "formatString": "0.00",
            "description": "Średnia wartość magnitudy wstrząsów w wybranym kontekście."
          },
          {
            "name": "Maks. magnituda",
            "expression": "MAX ( FactSeismic[Magnitude] )",
            "formatString": "0.00",
            "description": "Najsilniejszy wstrząs w wybranym kontekście."
          },
          {
            "name": "Średnia głębokość [km]",
            "expression": "AVERAGE ( FactSeismic[SeismicDepth] )",
            "formatString": "0.0",
            "description": "Średnia głębokość hipocentrum w kilometrach."
          },
          {
            "name": "Średnie MMI",
            "expression": "AVERAGEX ( FILTER ( FactSeismic, NOT ISBLANK ( FactSeismic[ModifiedMercalliIntensity] ) ), FactSeismic[ModifiedMercalliIntensity] )",
            "formatString": "0.00",
            "description": "Średnia intensywność wg skali Mercallego (tylko zdarzenia z dostępną oceną)."
          },
          {
            "name": "Wstrząsy M7+",
            "expression": "CALCULATE ( COUNTROWS ( FactSeismic ), FactSeismic[Magnitude] >= 7 )",
            "formatString": "#,##0",
            "description": "Liczba wstrząsów o magnitudzie ≥ 7.0 (Great / Mega)."
          }
        ],
        "partitions": [
          { "name": "FactSeismic", "source": { "type": "m", "expression": [ "SeismicDisasterDWH{[Schema=\"dbo\",Item=\"FactSeismic\"]}[Data]" ] } }
        ]
      },

      {
        "name": "FactDisaster",
        "columns": [
          { "name": "DisasterKey",         "dataType": "int64",   "sourceColumn": "DisasterKey",     "isKey": true },
          { "name": "StartDate",           "dataType": "int64",   "sourceColumn": "StartDate" },
          { "name": "EndDate",             "dataType": "int64",   "sourceColumn": "EndDate" },
          { "name": "GeographyKey",        "dataType": "int64",   "sourceColumn": "GeographyKey" },
          { "name": "SeverityDeathsKey",   "dataType": "int64",   "sourceColumn": "SeverityDeathsKey" },
          { "name": "SeverityAffectedKey", "dataType": "int64",   "sourceColumn": "SeverityAffectedKey" },
          { "name": "Latitude",            "dataType": "decimal", "sourceColumn": "Latitude" },
          { "name": "Longitude",           "dataType": "decimal", "sourceColumn": "Longitude" },
          { "name": "DurationDays",        "dataType": "int64",   "sourceColumn": "DurationDays",    "summarizeBy": "none" },
          { "name": "TotalDeaths",         "dataType": "int64",   "sourceColumn": "TotalDeaths",     "summarizeBy": "none" },
          { "name": "TotalAffected",       "dataType": "int64",   "sourceColumn": "TotalAffected",   "summarizeBy": "none" },
          { "name": "NumInjuries",         "dataType": "int64",   "sourceColumn": "NumInjuries",     "summarizeBy": "none" },
          { "name": "NumOtherAffected",    "dataType": "int64",   "sourceColumn": "NumOtherAffected","summarizeBy": "none" },
          { "name": "NumHomeless",         "dataType": "int64",   "sourceColumn": "NumHomeless",     "summarizeBy": "none" },
          { "name": "TotalDamageAdj",      "dataType": "int64",   "sourceColumn": "TotalDamageAdj",  "summarizeBy": "none" },
          { "name": "InsuredDamage",       "dataType": "int64",   "sourceColumn": "InsuredDamage",   "summarizeBy": "none" },
          { "name": "Tsunami",             "dataType": "boolean", "sourceColumn": "Tsunami" }
        ],
        "measures": [
          {
            "name": "Liczba katastrof",
            "expression": "COUNTROWS ( FactDisaster )",
            "formatString": "#,##0"
          },
          {
            "name": "Łączne ofiary",
            "expression": "SUM ( FactDisaster[TotalDeaths] )",
            "formatString": "#,##0"
          },
          {
            "name": "Łączni poszkodowani",
            "expression": "SUM ( FactDisaster[TotalAffected] )",
            "formatString": "#,##0"
          },
          {
            "name": "Straty materialne [USD]",
            "expression": "SUM ( FactDisaster[TotalDamageAdj] )",
            "formatString": "$#,##0,,\" M\"",
            "description": "Łączne straty materialne w milionach USD (wartość dostosowana do inflacji)."
          },
          {
            "name": "Straty ubezpieczone [USD]",
            "expression": "SUM ( FactDisaster[InsuredDamage] )",
            "formatString": "$#,##0,,\" M\""
          },
          {
            "name": "Wskaźnik ubezpieczenia [%]",
            "expression": "DIVIDE ( SUM ( FactDisaster[InsuredDamage] ), SUM ( FactDisaster[TotalDamageAdj] ) ) * 100",
            "formatString": "0.00\"%\"",
            "description": "Udział strat ubezpieczonych w łącznych stratach materialnych. Wyższa wartość = lepsza penetracja rynku ubezpieczeniowego."
          },
          {
            "name": "Luka ubezpieczeniowa [USD]",
            "expression": "SUM ( FactDisaster[TotalDamageAdj] ) - SUM ( FactDisaster[InsuredDamage] )",
            "formatString": "$#,##0,,\" M\"",
            "description": "Kwota strat nieubezpieczonych – potencjał rynku."
          },
          {
            "name": "Liczba katastrof z tsunami",
            "expression": "CALCULATE ( COUNTROWS ( FactDisaster ), FactDisaster[Tsunami] = TRUE () )",
            "formatString": "#,##0"
          },
          {
            "name": "Śr. czas trwania katastrofy [dni]",
            "expression": "AVERAGEX ( FILTER ( FactDisaster, NOT ISBLANK ( FactDisaster[DurationDays] ) ), FactDisaster[DurationDays] )",
            "formatString": "0.0"
          },
          {
            "name": "Śr. ofiary na katastrofę",
            "expression": "DIVIDE ( SUM ( FactDisaster[TotalDeaths] ), COUNTROWS ( FactDisaster ) )",
            "formatString": "#,##0.0"
          },
          {
            "name": "% katastrof z tsunami",
            "expression": "DIVIDE ( [Liczba katastrof z tsunami], [Liczba katastrof] ) * 100",
            "formatString": "0.0\"%\""
          }
        ],
        "partitions": [
          { "name": "FactDisaster", "source": { "type": "m", "expression": [ "SeismicDisasterDWH{[Schema=\"dbo\",Item=\"FactDisaster\"]}[Data]" ] } }
        ]
      },

      {
        "name": "BridgeDisasterSeismic",
        "columns": [
          { "name": "DisasterKey",  "dataType": "int64",   "sourceColumn": "DisasterKey" },
          { "name": "SeismicKey",   "dataType": "int64",   "sourceColumn": "SeismicKey" },
          { "name": "DistanceKM",   "dataType": "decimal", "sourceColumn": "DistanceKM",  "summarizeBy": "none" },
          { "name": "TimeLagDays",  "dataType": "int64",   "sourceColumn": "TimeLagDays", "summarizeBy": "none" }
        ],
        "measures": [
          {
            "name": "Wstrząsów na katastrofę",
            "expression": "DIVIDE ( COUNTROWS ( BridgeDisasterSeismic ), DISTINCTCOUNT ( BridgeDisasterSeismic[DisasterKey] ) )",
            "formatString": "0.0",
            "description": "Średnia liczba powiązanych wstrząsów fizycznych na jeden incydent EMDAT."
          },
          {
            "name": "Śr. odległość [km]",
            "expression": "AVERAGEX ( FILTER ( BridgeDisasterSeismic, NOT ISBLANK ( BridgeDisasterSeismic[DistanceKM] ) ), BridgeDisasterSeismic[DistanceKM] )",
            "formatString": "0.0"
          },
          {
            "name": "Śr. opóźnienie [dni]",
            "expression": "AVERAGEX ( FILTER ( BridgeDisasterSeismic, NOT ISBLANK ( BridgeDisasterSeismic[TimeLagDays] ) ), BridgeDisasterSeismic[TimeLagDays] )",
            "formatString": "0.0",
            "description": "Średni czas między wstrząsem fizycznym a oficjalną datą początku katastrofy w EMDAT."
          }
        ],
        "partitions": [
          { "name": "BridgeDisasterSeismic", "source": { "type": "m", "expression": [ "SeismicDisasterDWH{[Schema=\"dbo\",Item=\"BridgeDisasterSeismic\"]}[Data]" ] } }
        ]
      }

    ],

    "relationships": [
      { "name": "FactSeismic_Date",            "fromTable": "FactSeismic",          "fromColumn": "DateKey",          "toTable": "DimDate",            "toColumn": "DateKey" },
      { "name": "FactSeismic_Geography",       "fromTable": "FactSeismic",          "fromColumn": "GeographyKey",     "toTable": "DimGeography",       "toColumn": "GeographyKey" },
      { "name": "FactSeismic_Magnitude",       "fromTable": "FactSeismic",          "fromColumn": "MagnitudeKey",     "toTable": "DimMagnitude",       "toColumn": "MagnitudeKey" },
      { "name": "FactSeismic_Depth",           "fromTable": "FactSeismic",          "fromColumn": "SeismicDepthKey",  "toTable": "DimSeismicDepth",    "toColumn": "SeismicDepthKey" },
      { "name": "FactDisaster_StartDate",      "fromTable": "FactDisaster",         "fromColumn": "StartDate",        "toTable": "DimDate",            "toColumn": "DateKey" },
      { "name": "FactDisaster_EndDate",        "fromTable": "FactDisaster",         "fromColumn": "EndDate",          "toTable": "DimDate",            "toColumn": "DateKey",          "isActive": false },
      { "name": "FactDisaster_Geography",      "fromTable": "FactDisaster",         "fromColumn": "GeographyKey",     "toTable": "DimGeography",       "toColumn": "GeographyKey" },
      { "name": "FactDisaster_SevDeaths",      "fromTable": "FactDisaster",         "fromColumn": "SeverityDeathsKey","toTable": "DimSeverityDeaths",  "toColumn": "SeverityDeathsKey" },
      { "name": "FactDisaster_SevAffected",    "fromTable": "FactDisaster",         "fromColumn": "SeverityAffectedKey","toTable": "DimSeverityAffected","toColumn": "SeverityAffectedKey" },
      { "name": "Bridge_Disaster",             "fromTable": "BridgeDisasterSeismic","fromColumn": "DisasterKey",      "toTable": "FactDisaster",       "toColumn": "DisasterKey" },
      { "name": "Bridge_Seismic",              "fromTable": "BridgeDisasterSeismic","fromColumn": "SeismicKey",       "toTable": "FactSeismic",        "toColumn": "SeismicKey" }
    ]
  }
}
